readme.org for vac-vcp-cmp1a
Begun Mar 14, 2021
Builds on vac-vcp-cmp1, using current 2021 vcp.txt 
 from csl-orig/

This continues the work begun in vcpte-vcp-cmp1 folder.

Here, 'vac' refers to this Scharf version of Tirupati edition of Vacaspatyam.
Also, 'vcp' refers to the Cologne edition of Vacaspatyam.

* temp_vcp1a.txt
temp_vcp.txt is a copy from csl-orig/v02/vcp/vcp.txt at 03-14-2021

# make temp_vcp1a.txt in same format as ../vac-vcp-cmp1/vcp1.txt
# removes the '<L>, '<LEND>', lines, AND
# places [Pagexxx] on previous line
changes x¦ to <HI>{@x@}¦

python make_vcp1a.py temp_vcp.txt temp_vcp1a.txt

* vcp2a.txt
python make_vcp2a.py ../vac-vcp-cmp1/vac2.txt temp_vcp1a.txt vcp2a.txt

vcp2a.txt adds line number and code (vcp) and a 'diffcount' to lines of
temp_vcp1a.txt.

Example line 4:
../vac_vcp_cmp1/vac2.txt
000004:2:  te: vA+qa. </vkr><reN1> vizRO <q>akAro vizRuruddizwa ukArastu maheSvaraH

temp_vcp1a.txt:
<>vA qa . vizRO “akArovizRuruddizwOkArastu maheSvaraH .

vcp2a.txt:
000004:2:  te: vA+qa. </vkr><reN1> vizRO <q>akAro vizRuruddizwa ukArastu maheSvaraH


The diff number  in vcp2a.txt in this line is '2'.
This is the edit-distance between the 'te' line and the 'vcp' line,
 after adjustment (various removals of 'extraneous' information).

te-adj : vAqavizROakArovizRuruddizwaukArastumaheSvaraH
vcp-adj: vAqavizROakArovizRuruddizwOkArastumaheSvaraH

edit-distance = 2
